@startuml AirConditionController

class AirConditionController {
  - {static} instance: AirConditionController
  - AirConditionController()
  + {static} getInstance(): AirConditionController
  + setTemperature(temperature: int)
  + turnOn()
  + turnOff()
}

@enduml
